# Generated by Django 4.2.10 on 2024-02-26 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0002_rename_series_id_question_assignment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcase',
            name='show',
        ),
        migrations.AlterField(
            model_name='question',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
