# Generated by Django 4.2.10 on 2024-02-26 13:51

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('judge', '0002_rename_series_id_question_assignment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Submission Summary',
                'verbose_name_plural': 'Submission Summary',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('judge.submission',),
        ),
    ]
